/* Generated By:JavaCC: Do not edit this line. SPARQLParser12ForHeFQUINConstants.java */
package se.liu.ida.hefquin.jenaext.sparql.lang.sparql_12_hefquin.javacc ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPARQLParser12ForHeFQUINConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int IRIref = 9;
  /** RegularExpression Id. */
  int PNAME_NS = 10;
  /** RegularExpression Id. */
  int PNAME_LN = 11;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 12;
  /** RegularExpression Id. */
  int VAR1 = 13;
  /** RegularExpression Id. */
  int VAR2 = 14;
  /** RegularExpression Id. */
  int LANG_DIR = 15;
  /** RegularExpression Id. */
  int A2Z = 16;
  /** RegularExpression Id. */
  int A2ZN = 17;
  /** RegularExpression Id. */
  int KW_A = 18;
  /** RegularExpression Id. */
  int BASE = 19;
  /** RegularExpression Id. */
  int PREFIX = 20;
  /** RegularExpression Id. */
  int VERSION = 21;
  /** RegularExpression Id. */
  int SELECT = 22;
  /** RegularExpression Id. */
  int DISTINCT = 23;
  /** RegularExpression Id. */
  int REDUCED = 24;
  /** RegularExpression Id. */
  int DESCRIBE = 25;
  /** RegularExpression Id. */
  int CONSTRUCT = 26;
  /** RegularExpression Id. */
  int ASK = 27;
  /** RegularExpression Id. */
  int LIMIT = 28;
  /** RegularExpression Id. */
  int OFFSET = 29;
  /** RegularExpression Id. */
  int ORDER = 30;
  /** RegularExpression Id. */
  int BY = 31;
  /** RegularExpression Id. */
  int VALUES = 32;
  /** RegularExpression Id. */
  int UNDEF = 33;
  /** RegularExpression Id. */
  int ASC = 34;
  /** RegularExpression Id. */
  int DESC = 35;
  /** RegularExpression Id. */
  int NAMED = 36;
  /** RegularExpression Id. */
  int FROM = 37;
  /** RegularExpression Id. */
  int WHERE = 38;
  /** RegularExpression Id. */
  int AND = 39;
  /** RegularExpression Id. */
  int GRAPH = 40;
  /** RegularExpression Id. */
  int OPTIONAL = 41;
  /** RegularExpression Id. */
  int UNION = 42;
  /** RegularExpression Id. */
  int MINUS_P = 43;
  /** RegularExpression Id. */
  int BIND = 44;
  /** RegularExpression Id. */
  int SERVICE = 45;
  /** RegularExpression Id. */
  int UNFOLD = 46;
  /** RegularExpression Id. */
  int TRIPLE = 47;
  /** RegularExpression Id. */
  int IS_TRIPLE = 48;
  /** RegularExpression Id. */
  int SUBJECT = 49;
  /** RegularExpression Id. */
  int PREDICATE = 50;
  /** RegularExpression Id. */
  int OBJECT = 51;
  /** RegularExpression Id. */
  int EXISTS = 52;
  /** RegularExpression Id. */
  int NOT = 53;
  /** RegularExpression Id. */
  int AS = 54;
  /** RegularExpression Id. */
  int GROUP = 55;
  /** RegularExpression Id. */
  int HAVING = 56;
  /** RegularExpression Id. */
  int SEPARATOR = 57;
  /** RegularExpression Id. */
  int AGG = 58;
  /** RegularExpression Id. */
  int COUNT = 59;
  /** RegularExpression Id. */
  int MIN = 60;
  /** RegularExpression Id. */
  int MAX = 61;
  /** RegularExpression Id. */
  int SUM = 62;
  /** RegularExpression Id. */
  int AVG = 63;
  /** RegularExpression Id. */
  int SAMPLE = 64;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 65;
  /** RegularExpression Id. */
  int FILTER = 66;
  /** RegularExpression Id. */
  int BOUND = 67;
  /** RegularExpression Id. */
  int COALESCE = 68;
  /** RegularExpression Id. */
  int IN = 69;
  /** RegularExpression Id. */
  int IF = 70;
  /** RegularExpression Id. */
  int BNODE = 71;
  /** RegularExpression Id. */
  int IRI = 72;
  /** RegularExpression Id. */
  int URI = 73;
  /** RegularExpression Id. */
  int STR = 74;
  /** RegularExpression Id. */
  int STRLANG = 75;
  /** RegularExpression Id. */
  int STRLANGDIR = 76;
  /** RegularExpression Id. */
  int STRDT = 77;
  /** RegularExpression Id. */
  int DTYPE = 78;
  /** RegularExpression Id. */
  int LANG = 79;
  /** RegularExpression Id. */
  int LANGMATCHES = 80;
  /** RegularExpression Id. */
  int LANGDIR = 81;
  /** RegularExpression Id. */
  int IS_URI = 82;
  /** RegularExpression Id. */
  int IS_IRI = 83;
  /** RegularExpression Id. */
  int IS_BLANK = 84;
  /** RegularExpression Id. */
  int IS_LITERAL = 85;
  /** RegularExpression Id. */
  int IS_NUMERIC = 86;
  /** RegularExpression Id. */
  int HAS_LANG = 87;
  /** RegularExpression Id. */
  int HAS_LANGDIR = 88;
  /** RegularExpression Id. */
  int REGEX = 89;
  /** RegularExpression Id. */
  int SAME_TERM = 90;
  /** RegularExpression Id. */
  int SAME_VALUE = 91;
  /** RegularExpression Id. */
  int RAND = 92;
  /** RegularExpression Id. */
  int ABS = 93;
  /** RegularExpression Id. */
  int CEIL = 94;
  /** RegularExpression Id. */
  int FLOOR = 95;
  /** RegularExpression Id. */
  int ROUND = 96;
  /** RegularExpression Id. */
  int CONCAT = 97;
  /** RegularExpression Id. */
  int SUBSTR = 98;
  /** RegularExpression Id. */
  int STRLEN = 99;
  /** RegularExpression Id. */
  int REPLACE = 100;
  /** RegularExpression Id. */
  int UCASE = 101;
  /** RegularExpression Id. */
  int LCASE = 102;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 103;
  /** RegularExpression Id. */
  int CONTAINS = 104;
  /** RegularExpression Id. */
  int STRSTARTS = 105;
  /** RegularExpression Id. */
  int STRENDS = 106;
  /** RegularExpression Id. */
  int STRBEFORE = 107;
  /** RegularExpression Id. */
  int STRAFTER = 108;
  /** RegularExpression Id. */
  int YEAR = 109;
  /** RegularExpression Id. */
  int MONTH = 110;
  /** RegularExpression Id. */
  int DAY = 111;
  /** RegularExpression Id. */
  int HOURS = 112;
  /** RegularExpression Id. */
  int MINUTES = 113;
  /** RegularExpression Id. */
  int SECONDS = 114;
  /** RegularExpression Id. */
  int TIMEZONE = 115;
  /** RegularExpression Id. */
  int TZ = 116;
  /** RegularExpression Id. */
  int NOW = 117;
  /** RegularExpression Id. */
  int UUID = 118;
  /** RegularExpression Id. */
  int STRUUID = 119;
  /** RegularExpression Id. */
  int MD5 = 120;
  /** RegularExpression Id. */
  int SHA1 = 121;
  /** RegularExpression Id. */
  int SHA224 = 122;
  /** RegularExpression Id. */
  int SHA256 = 123;
  /** RegularExpression Id. */
  int SHA384 = 124;
  /** RegularExpression Id. */
  int SHA512 = 125;
  /** RegularExpression Id. */
  int TRUE = 126;
  /** RegularExpression Id. */
  int FALSE = 127;
  /** RegularExpression Id. */
  int DATA = 128;
  /** RegularExpression Id. */
  int INSERT = 129;
  /** RegularExpression Id. */
  int DELETE = 130;
  /** RegularExpression Id. */
  int INSERT_DATA = 131;
  /** RegularExpression Id. */
  int DELETE_DATA = 132;
  /** RegularExpression Id. */
  int DELETE_WHERE = 133;
  /** RegularExpression Id. */
  int LOAD = 134;
  /** RegularExpression Id. */
  int CLEAR = 135;
  /** RegularExpression Id. */
  int CREATE = 136;
  /** RegularExpression Id. */
  int ADD = 137;
  /** RegularExpression Id. */
  int MOVE = 138;
  /** RegularExpression Id. */
  int COPY = 139;
  /** RegularExpression Id. */
  int META = 140;
  /** RegularExpression Id. */
  int SILENT = 141;
  /** RegularExpression Id. */
  int PARAMS = 142;
  /** RegularExpression Id. */
  int DROP = 143;
  /** RegularExpression Id. */
  int INTO = 144;
  /** RegularExpression Id. */
  int TO = 145;
  /** RegularExpression Id. */
  int DFT = 146;
  /** RegularExpression Id. */
  int ALL = 147;
  /** RegularExpression Id. */
  int WITH = 148;
  /** RegularExpression Id. */
  int USING = 149;
  /** RegularExpression Id. */
  int DIGITS = 150;
  /** RegularExpression Id. */
  int INTEGER = 151;
  /** RegularExpression Id. */
  int DECIMAL = 152;
  /** RegularExpression Id. */
  int DOUBLE = 153;
  /** RegularExpression Id. */
  int EXPONENT = 154;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 155;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 156;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 157;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 158;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 159;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 160;
  /** RegularExpression Id. */
  int QUOTE_3D = 161;
  /** RegularExpression Id. */
  int QUOTE_3S = 162;
  /** RegularExpression Id. */
  int ECHAR = 163;
  /** RegularExpression Id. */
  int UCHAR = 164;
  /** RegularExpression Id. */
  int UCHAR4 = 165;
  /** RegularExpression Id. */
  int UCHAR8 = 166;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 167;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 168;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 169;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 170;
  /** RegularExpression Id. */
  int LPAREN = 171;
  /** RegularExpression Id. */
  int RPAREN = 172;
  /** RegularExpression Id. */
  int NIL = 173;
  /** RegularExpression Id. */
  int LBRACE = 174;
  /** RegularExpression Id. */
  int RBRACE = 175;
  /** RegularExpression Id. */
  int LBRACKET = 176;
  /** RegularExpression Id. */
  int RBRACKET = 177;
  /** RegularExpression Id. */
  int ANON = 178;
  /** RegularExpression Id. */
  int SEMICOLON = 179;
  /** RegularExpression Id. */
  int COMMA = 180;
  /** RegularExpression Id. */
  int DOT = 181;
  /** RegularExpression Id. */
  int EQ = 182;
  /** RegularExpression Id. */
  int NE = 183;
  /** RegularExpression Id. */
  int GT = 184;
  /** RegularExpression Id. */
  int LT = 185;
  /** RegularExpression Id. */
  int LE = 186;
  /** RegularExpression Id. */
  int GE = 187;
  /** RegularExpression Id. */
  int L_TRIPLE = 188;
  /** RegularExpression Id. */
  int R_TRIPLE = 189;
  /** RegularExpression Id. */
  int LT2 = 190;
  /** RegularExpression Id. */
  int GT2 = 191;
  /** RegularExpression Id. */
  int L_ANN = 192;
  /** RegularExpression Id. */
  int R_ANN = 193;
  /** RegularExpression Id. */
  int TILDE = 194;
  /** RegularExpression Id. */
  int BANG = 195;
  /** RegularExpression Id. */
  int COLON = 196;
  /** RegularExpression Id. */
  int SC_OR = 197;
  /** RegularExpression Id. */
  int SC_AND = 198;
  /** RegularExpression Id. */
  int PLUS = 199;
  /** RegularExpression Id. */
  int MINUS = 200;
  /** RegularExpression Id. */
  int STAR = 201;
  /** RegularExpression Id. */
  int SLASH = 202;
  /** RegularExpression Id. */
  int DATATYPE = 203;
  /** RegularExpression Id. */
  int AT = 204;
  /** RegularExpression Id. */
  int VBAR = 205;
  /** RegularExpression Id. */
  int CARAT = 206;
  /** RegularExpression Id. */
  int QMARK = 207;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 208;
  /** RegularExpression Id. */
  int PN_CHARS_U = 209;
  /** RegularExpression Id. */
  int PN_CHARS = 210;
  /** RegularExpression Id. */
  int PN_PREFIX = 211;
  /** RegularExpression Id. */
  int PN_LOCAL = 212;
  /** RegularExpression Id. */
  int VARNAME = 213;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 214;
  /** RegularExpression Id. */
  int PLX = 215;
  /** RegularExpression Id. */
  int HEX = 216;
  /** RegularExpression Id. */
  int PERCENT = 217;
  /** RegularExpression Id. */
  int UNKNOWN = 218;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANG_DIR>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"version\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"values\"",
    "\"undef\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"bind\"",
    "\"service\"",
    "\"unfold\"",
    "\"TRIPLE\"",
    "\"isTRIPLE\"",
    "\"SUBJECT\"",
    "\"PREDICATE\"",
    "\"OBJECT\"",
    "\"exists\"",
    "\"not\"",
    "\"as\"",
    "\"group\"",
    "\"having\"",
    "\"separator\"",
    "\"agg\"",
    "\"count\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "\"avg\"",
    "\"sample\"",
    "\"group_concat\"",
    "\"filter\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"str\"",
    "\"strlang\"",
    "\"strlangdir\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"langdir\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"hasLang\"",
    "\"hasLangDir\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"sameValue\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"UUID\"",
    "\"STRUUID\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA224\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"true\"",
    "\"false\"",
    "\"data\"",
    "\"insert\"",
    "\"delete\"",
    "<INSERT_DATA>",
    "<DELETE_DATA>",
    "<DELETE_WHERE>",
    "\"load\"",
    "\"clear\"",
    "\"create\"",
    "\"add\"",
    "\"move\"",
    "\"copy\"",
    "\"meta\"",
    "\"silent\"",
    "\"params\"",
    "\"drop\"",
    "\"into\"",
    "\"to\"",
    "\"default\"",
    "\"all\"",
    "\"with\"",
    "\"using\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<<(\"",
    "\")>>\"",
    "\"<<\"",
    "\">>\"",
    "\"{|\"",
    "\"|}\"",
    "\"~\"",
    "\"!\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\"|\"",
    "\"^\"",
    "\"?\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
