SELECT ?predicate ?object WHERE {
  VALUES ( ?s1 ?s2 ?s3 ) {
    ( <http://localhost:8080/tpf/dbpedia> <http://localhost:8080/brtpf/nyt> <http://localhost:8080/brtpf/nyt> )
  }
  {
    SERVICE ?s1 { <http://dbpedia.org/resource/Barack_Obama> ?predicate ?object }
  }
  UNION {
    SERVICE ?s2 { ?subject <http://www.w3.org/2002/07/owl#sameAs> <http://dbpedia.org/resource/Barack_Obama> }
    SERVICE ?s3 { ?subject ?predicate ?object }
  }
}