SELECT DISTINCT ?proceedings ?paper ?p WHERE {
  VALUES ( ?s1 ?s2 ?s3 ) {
    ( <http://localhost:8080/tpf/swdfood> <http://localhost:8080/tpf/swdfood> <http://localhost:8080/tpf/swdfood> )
  }
  SERVICE ?s1 { ?proceedings <http://data.semanticweb.org/ns/swc/ontology#relatedToEvent>  <http://data.semanticweb.org/conference/eswc/2010> . }
  SERVICE ?s2 { ?paper <http://data.semanticweb.org/ns/swc/ontology#isPartOf> ?proceedings . }
  SERVICE ?s3 { ?paper <http://swrc.ontoware.org/ontology#author> ?p . }
}