SELECT ?drug ?keggUrl ?chebiImage WHERE {
  VALUES ( ?s1 ?s2 ?s3 ?s4 ?s5 ?s6 ) {
    ( <http://localhost:8080/tpf/drugbank> <http://localhost:8080/tpf/drugbank> <http://localhost:8080/brtpf/kegg> <http://localhost:8080/tpf/drugbank> <http://localhost:8080/sparql/chebi/> <http://localhost:8080/sparql/chebi/> )
  }
  SERVICE ?s1 { ?drug <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/drugs> . }
  SERVICE ?s2 { ?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/keggCompoundId> ?keggDrug . }
  SERVICE ?s3 { ?keggDrug <http://bio2rdf.org/ns/bio2rdf#url> ?keggUrl . }
  SERVICE ?s4 { ?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/genericName> ?drugBankName . }
  SERVICE ?s5 { ?chebiDrug <http://purl.org/dc/elements/1.1/title> ?drugBankName . }
  SERVICE ?s6 { ?chebiDrug <http://bio2rdf.org/ns/bio2rdf#image> ?chebiImage . }
}