SELECT DISTINCT ?paper ?p ?x ?n WHERE {
  VALUES ( ?s1 ?s2 ?s3 ?s4 ) {
    ( <http://localhost:8080/tpf/swdfood> <http://localhost:8080/tpf/swdfood> <http://localhost:8080/tpf/swdfood> <http://localhost:8080/tpf/swdfood> )
  }
  SERVICE ?s1 { ?paper <http://data.semanticweb.org/ns/swc/ontology#isPartOf> <http://data.semanticweb.org/conference/iswc/2008/poster_demo_proceedings> . }
  SERVICE ?s2 { ?paper <http://swrc.ontoware.org/ontology#author> ?p . }
  SERVICE ?s3 { ?p <http://www.w3.org/2002/07/owl#sameAs> ?x . }
  SERVICE ?s4 { ?p <http://www.w3.org/2000/01/rdf-schema#label> ?n . }
}