SELECT DISTINCT * WHERE {
  VALUES ( ?s1 ?s2 ) {
    ( <http://localhost/sparql/geonames> <http://localhost/sparql/geonames> )
  }
  SERVICE ?s1 { ?x <http://www.geonames.org/ontology#parentFeature> <http://sws.geonames.org/2921044/> . }
  SERVICE ?s2 { ?x <http://www.geonames.org/ontology#name> ?n . }
}