PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX wdt:    <http://www.wikidata.org/prop/direct/>
PREFIX wd:     <http://www.wikidata.org/entity/>
PREFIX ex:     <http://example.org/>

# This query accesses the Web API of the Open Disease Data service by using
# requests that are formed based on data obtained from a SPARQL endpoint.
# More specifically, the query obtains the ISO country codes of all European
# countries from the SPARQL endpoint of the wikidata Knowledge Graph and,
# then, uses these ISO codes to request Covid-19 statistics from the Web API.
#
# Notice that one of the ISO codes obtained from Wikidata is "XK" for Kosovo,
# which is not recognized by the Web API; that is, the request with this ISO
# code results in a 404 error. Therefore, the SERVICE clause for the Web API
# ignores the solution mapping with this ISO code.

SELECT * WHERE {
	SERVICE <https://query.wikidata.org/sparql> {
		?country wdt:P31 wd:Q6256 ;       # instance of country
		         wdt:P30 wd:Q46 ;         # located in Europe
		         wdt:P297 ?isoCode ;      # ISO country code
		         rdfs:label ?countryLabel .
		FILTER( LANG(?countryLabel) = "en" )
	}

	SERVICE <http://example.org/Covid19APIWrapper> PARAMS(?isoCode AS "country") {
		?x ex:totalCases ?totalCases .
		?x ex:updated ?updated .
		?x ex:todayCases ?todayCases .
		?x ex:totalDeaths ?totalDeaths .
		?x ex:todayDeaths ?todayDeaths .
		?x ex:totalRecovered ?totalRecovered .
	}
}
