PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX dbo:    <http://dbpedia.org/ontology/>

# This is essentially the same query as the previous one. The only difference
# is that, instead of using the SPARQL endpoint of DBpedia, this one uses the
# TPF server of DBpedia.
# The query plan will be different because the two triple patterns of the first
# SERVICE clause cannot be sent as a single request to the TPF server, and also
# the FILTER needs to be locally now (i.e., by HeFQUIN itself).

SELECT * WHERE {
	SERVICE <http://fragments.dbpedia.org/2016-04/en> {
		<http://dbpedia.org/resource/Berlin> dbo:country ?c .
		?c owl:sameAs ?cc
		FILTER ( CONTAINS(STR(?cc), "wikidata" ) )
	}

	SERVICE <https://query.wikidata.org/sparql> {
		?cc rdfs:label ?o
	}
}
