PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX dbo:    <http://dbpedia.org/ontology/>
PREFIX geo:    <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX ex:     <http://example.org/>

# This query accesses the Web API of the Open-Meteo weather service by using
# requests that are formed based on data obtained from a SPARQL endpoint.
# More specifically, the query obtains the geographic coordinates of cities
# in Croatia from the SPARQL endpoint of the DBpedia Knowledge Graph and,
# then, uses these coordinates to request the current temperature and wind
# speed in these cities from the Web API.

SELECT * WHERE
{
	SERVICE <https://qlever.dev/api/dbpedia>
	{
		?city rdf:type dbo:City ;
		      geo:lat ?lat ;
		      geo:long ?long ;
		      dbo:country <http://dbpedia.org/resource/Croatia>
	}

	SERVICE <http://example.org/OpenMeteoWrapper> PARAMS(?lat AS "latitude",
	                                                     ?long AS "longitude")
	{
		?x ex:temperature ?temp .
		?x ex:windSpeed ?wind .
	}
}
