PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX dbo:    <http://dbpedia.org/ontology/>
PREFIX dbr:    <http://dbpedia.org/resource/>
PREFIX ex:     <http://example.org/>

# This query accesses the Web API of the Open Library service by using
# requests that are formed based on data obtained from a SPARQL endpoint.
# More specifically, the query obtains the names of winners of the Nobel
# Prize in Literature from the SPARQL endpoint of the DBpedia Knowledge
# Graph and, then, uses these names to request information about books
# authored by these winners from the Web API.

#SELECT ?authorName ?bookTitle ?publishYear WHERE {
SELECT * WHERE {
  BIND(3 AS ?bookLimit)

  SERVICE <http://dbpedia.org/sparql> {
    ?author dbo:award dbr:Nobel_Prize_in_Literature ;
            rdfs:label ?authorName .
    FILTER( lang(?authorName) = "en" )
  }

FILTER ( CONTAINS(?authorName, "Annie" ) )

  SERVICE <http://example.org/OpenLibraryWrapper> PARAMS( ?authorName AS "author",
                                                          ?bookLimit AS "limit" ) {
#    ?book ex:title ?bookTitle ;
#          ex:firstPublished ?publishYear .
?s ?p ?o
  }
}
