PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX dbo:    <http://dbpedia.org/ontology/>
PREFIX geo:    <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX ex:     <http://example.org/>

# This query is similar to the previous one (obtaining weather information from
# the Web API of the Open-Meteo service, for a location whose geo coordinates
# are obtained from DBpedia) but it also demonstrates that the RML processor of
# HeFQUIN creates cdt:Map literals for cases in which the object map of an RML
# triples map refers to a JSON object (rather than to scalars value within a
# JSON object). The BIND clauses at the end of the query applies a function
# that has been defined for cdt:Map literals, and the UNFOLD operator unfolds
# the cdt:List literal obtained from the cdt:keys function.

SELECT * WHERE {
	SERVICE <http://dbpedia.org/sparql> {
		<http://dbpedia.org/resource/Berlin> geo:lat ?lat ;
		                                     geo:long ?long .
	}

	BIND ( "temperature_2m,wind_speed_10m" AS ?req)

	SERVICE <http://example.org/OpenMeteoWrapper> PARAMS(?lat AS "latitude",
	                                                     ?long AS "longitude",
	                                                     ?req AS "current") {
		?x ex:current ?c .
	}

	BIND ( cdt:keys(?c) AS ?keys )
	UNFOLD( ?keys AS ?key )
}
