package se.liu.ida.hefquin.vocabulary;

/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from feddesc.ttl 
 * @author Auto-generated by schemagen on 30 Apr 2026 08:43 
 */
public class FDVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://w3id.org/hefquin/feddesc#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The network address (URI) of the endpoint of the federation member.</p> */
    public static final Property endpointAddress = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#endpointAddress" );
    
    /** <p>An example URI of a fragment for the fragment interface.</p> */
    public static final Property exampleFragmentAddress = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#exampleFragmentAddress" );
    
    /** <p>The interface for accessing the federation member.</p> */
    public static final Property interface_ = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#interface" );
    
    /** <p>Mapping configuration for translating non-RDF data models to RDF (e.g., GraphQL, 
     *  PG).</p>
     */
    public static final Property mappingConfiguration = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#mappingConfiguration" );
    
    /** <p>The type of values to be used for a variable part of a URI template. This 
     *  type is expected to be specified as a datatype URI (e.g., xsd:string, xsd:float).</p>
     */
    public static final Property paramType = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#paramType" );
    
    /** <p>List of RML triples maps that define the mapping for a wrapper. The elements 
     *  of such a list are expected to be of type rml:TriplesMap. ATTENTION: for the 
     *  time being, these triples maps must all be normalized as per the definition 
     *  in Section 5 of the paper titled 'An Algebraic Foundation for Knowledge Graph 
     *  Construction'.</p>
     */
    public static final Property rmlTriplesMaps = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#rmlTriplesMaps" );
    
    /** <p>The URI via which the federation member is identified in a SERVICE clause.</p> */
    public static final Property serviceURI = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#serviceURI" );
    
    /** <p>The data retrieval protocol supported by the interface.</p> */
    public static final Property supportedProtocol = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#supportedProtocol" );
    
    /** <p>The template for creating URIs that can be used for issuing requests to the 
     *  interface. The template is captured as a hydra:IriTemplate, which must have 
     *  a hydra:template property and, if the template contains variable parts, there 
     *  must also be a hydra:mapping property for each of these variable parts.</p>
     */
    public static final Property uriTemplate = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#uriTemplate" );
    
    /** <p>Path to a file with RDF mappings to align different vocabularies.</p> */
    public static final Property vocabularyMappingsFile = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#vocabularyMappingsFile" );
    
    /** <p>The wrapper of a wrapped federation member.</p> */
    public static final Property wrapper = M_MODEL.createProperty( "http://w3id.org/hefquin/feddesc#wrapper" );
    
    /** <p>Instances of this class represent the different protocols to be used when 
     *  interacting with the interface of a federation member.</p>
     */
    public static final Resource DataRetrievalProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#DataRetrievalProtocol" );
    
    /** <p>An entity that is part of the federation and provides access to data via a 
     *  specific interface. Every federation member must have an fd:serviceURI property 
     *  and an fd:interface property. This class is a superclass of any kind of federation 
     *  member and should not be used directly within federation descriptions. Concrete 
     *  types of federation members, to be used in federation descriptions, are captured 
     *  by the subclasses of this class.</p>
     */
    public static final Resource FederationMember = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#FederationMember" );
    
    /** <p>An interface that can be accessed via a single, fixed endpoint address. Every 
     *  such interface must have an fd:endpointAddress property and an fd:supportedProtocol 
     *  property. The value for the fd:supportedProtocol property is expected to be 
     *  one of the following: fd:SPARQLProtocol, fd:BoltProtocol, fd:GraphQLProtocol, 
     *  or fd:GenericWebAPIProtocol.</p>
     */
    public static final Resource FixedEndpointInterface = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#FixedEndpointInterface" );
    
    /** <p>An interface that can be accessed via URIs that denote fragments (i.e., specific 
     *  subsets) of the dataset of the corresponding federation member, where the 
     *  way in which these URIs are formed is communicated in responses to requests 
     *  to such an interface. Every such interface must have an fd:exampleFragmentAddress 
     *  property and an fd:supportedProtocol property. The value for the fd:supportedProtocol 
     *  property is expected to be either fd:TPFProtocol or fd:brTPFProtocol.</p>
     */
    public static final Resource FragmentInterface = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#FragmentInterface" );
    
    /** <p>An interface is a means to issue data retrieval requests to a federation member. 
     *  This class is a superclass of any kind of interface and should not be used 
     *  directly within federation descriptions. Concrete types of interfaces, to 
     *  be used in federation descriptions, are captured by the subclasses of this 
     *  class.</p>
     */
    public static final Resource Interface = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#Interface" );
    
    /** <p>A federation member whose interface exposes RDF data. Every such federation 
     *  member must have the two properties that are expected for any kind of federation 
     *  member (i.e., fd:serviceURI and fd:interface), where the fd:interface may 
     *  be either an fd:FixedEndpointInterface with the fd:supportedProtocol being 
     *  fd:SPARQLProtocol or an fd:FragmentInterface. Additionally, an RDF-based federation 
     *  member may have an fd:vocabularyMappingsFile property.</p>
     */
    public static final Resource RDFBasedFederationMember = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#RDFBasedFederationMember" );
    
    /** <p>An interface that can be accessed via request URIs that can be created based 
     *  on a URI template. Every such interface must have an fd:uriTemplate property 
     *  and an fd:supportedProtocol property. For the time being, the value for the 
     *  fd:supportedProtocol property is expected to be fd:GenericWebAPIProtocol.</p>
     */
    public static final Resource TemplateBasedInterface = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#TemplateBasedInterface" );
    
    /** <p>A federation member that provides access to non-RDF data, for which it is 
     *  associated with a wrapper that defines and RDF view of the data of that federation 
     *  member. In addition to the properties that are expected for any kind of federation 
     *  member (i.e., fd:serviceURI and fd:interface), such a wrapped federation member 
     *  must have an fd:wrapper property.</p>
     */
    public static final Resource WrappedFederationMember = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#WrappedFederationMember" );
    
    /** <p>A wrapper provides a mapping for data of federation members that do not support 
     *  RDF and SPARQL natively. For the time being, every such wrapper must have 
     *  either an fd:rmlTriplesMaps property or an fd:mappingConfiguration property. 
     *  In particular, for wrappers associated with a federation member whose interface 
     *  has fd:GenericWebAPIProtocol as the fd:supportedProtocol, the wrapper must 
     *  have an fd:rmlTriplesMaps property; and for wrappers associated with a federation 
     *  member whose interface has fd:BoltProtocol or fd:GraphQLProtocol as the fd:supportedProtocol, 
     *  the wrapper must have an fd:mappingConfiguration property.</p>
     */
    public static final Resource Wrapper = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#Wrapper" );
    
    /** <p>The protocol to be used when interacting with a Neo4j server.</p> */
    public static final Resource BoltProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#BoltProtocol" );
    
    /** <p>The protocol to be used when interacting with a generic Web API.</p> */
    public static final Resource GenericWebAPIProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#GenericWebAPIProtocol" );
    
    /** <p>The protocol to be used when interacting with a GraphQL server.</p> */
    public static final Resource GraphQLProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#GraphQLProtocol" );
    
    /** <p>The protocol to be used for SPARQL endpoints.</p> */
    public static final Resource SPARQLProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#SPARQLProtocol" );
    
    /** <p>The protocol to be used when interacting with a TPF server.</p> */
    public static final Resource TPFProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#TPFProtocol" );
    
    /** <p>The protocol to be used when interacting with a brTPF server.</p> */
    public static final Resource brTPFProtocol = M_MODEL.createResource( "http://w3id.org/hefquin/feddesc#brTPFProtocol" );
    
}
