package se.liu.ida.hefquin.vocabulary;

/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from https://www.w3.org/ns/hydra/core.jsonld 
 * @author Auto-generated by schemagen on 27 Jan 2026 17:04 
 */
public class HydraVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/hydra/core#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>Determines whether the provided set of header values is closed or not.</p> */
    public static final Property closedSet = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#closedSet" );
    
    /** <p>A description.</p> */
    public static final Property description = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#description" );
    
    /** <p>Specification of the header expected by the operation.</p> */
    public static final Property expectsHeader = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#expectsHeader" );
    
    /** <p>Hint on what kind of extensions are in use.</p> */
    public static final Property extension = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#extension" );
    
    /** <p>A property representing a freetext query.</p> */
    public static final Property freetextQuery = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#freetextQuery" );
    
    /** <p>Name of the header.</p> */
    public static final Property headerName = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#headerName" );
    
    /** <p>Instructs to limit set only to N elements.</p> */
    public static final Property limit = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#limit" );
    
    /** <p>A variable-to-property mapping of the IRI template.</p> */
    public static final Property mapping = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#mapping" );
    
    /** <p>The HTTP method.</p> */
    public static final Property method = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#method" );
    
    /** <p>Instructs to skip N elements of the set.</p> */
    public static final Property offset = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#offset" );
    
    /** <p>Instructs to provide a specific page of the collection at a given index.</p> */
    public static final Property pageIndex = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#pageIndex" );
    
    /** <p>Instructs to provide a specific page reference of the collection.</p> */
    public static final Property pageReference = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#pageReference" );
    
    /** <p>Possible value of the header.</p> */
    public static final Property possibleValue = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#possibleValue" );
    
    /** <p>A property</p> */
    public static final Property property = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#property" );
    
    /** <p>True if the client can retrieve the property's value, false otherwise.</p> */
    public static final Property readable = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#readable" );
    
    /** <p>True if the property is required, false otherwise.</p> */
    public static final Property required = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#required" );
    
    public static final Property resolveRelativeUsing = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#resolveRelativeUsing" );
    
    /** <p>Name of the header returned by the operation.</p> */
    public static final Property returnsHeader = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#returnsHeader" );
    
    /** <p>The HTTP status code. Please note it may happen this value will be different 
     *  to actual status code received.</p>
     */
    public static final Property statusCode = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#statusCode" );
    
    /** <p>A templated string with placeholders. The literal's datatype indicates the 
     *  template syntax; if not specified, hydra:Rfc6570Template is assumed.</p>
     */
    public static final Property template = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#template" );
    
    /** <p>A title, often used along with a description.</p> */
    public static final Property title = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#title" );
    
    /** <p>The total number of items referenced by a collection.</p> */
    public static final Property totalItems = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#totalItems" );
    
    /** <p>An IRI template variable</p> */
    public static final Property variable = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#variable" );
    
    /** <p>The representation format to use when expanding the IRI template.</p> */
    public static final Property variableRepresentation = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#variableRepresentation" );
    
    /** <p>True if the client can change the property's value, false otherwise.</p> */
    public static final Property writable = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#writable" );
    
    /** <p>The Hydra API documentation class</p> */
    public static final Resource ApiDocumentation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#ApiDocumentation" );
    
    /** <p>Provides a base abstract for base Uri source for Iri template resolution.</p> */
    public static final Resource BaseUriSource = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#BaseUriSource" );
    
    /** <p>A representation that serializes just the lexical form of a variable value, 
     *  but omits language and type information.</p>
     */
    public static final Resource BasicRepresentation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#BasicRepresentation" );
    
    /** <p>The class of Hydra classes.</p> */
    public static final Resource Class = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Class" );
    
    /** <p>A collection holding references to a number of related resources.</p> */
    public static final Resource Collection = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Collection" );
    
    /** <p>A runtime error, used to report information beyond the returned status code.</p> */
    public static final Resource Error = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Error" );
    
    /** <p>A representation that serializes a variable value including its language and 
     *  type information and thus differentiating between IRIs and literals.</p>
     */
    public static final Resource ExplicitRepresentation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#ExplicitRepresentation" );
    
    /** <p>The class of IRI templates.</p> */
    public static final Resource IriTemplate = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#IriTemplate" );
    
    /** <p>A mapping from an IRI template variable to a property.</p> */
    public static final Resource IriTemplateMapping = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#IriTemplateMapping" );
    
    /** <p>The class of properties representing links.</p> */
    public static final Resource Link = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Link" );
    
    /** <p>States that the link's context IRI, as defined in RFC 5988, should be used 
     *  as the base Uri</p>
     */
    public static final Resource LinkContext = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#LinkContext" );
    
    /** <p>An operation.</p> */
    public static final Resource Operation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Operation" );
    
    /** <p>A PartialCollectionView describes a partial view of a Collection. Multiple 
     *  PartialCollectionViews can be connected with the the next/previous properties 
     *  to allow a client to retrieve all members of the collection.</p>
     */
    public static final Resource PartialCollectionView = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#PartialCollectionView" );
    
    /** <p>The class of dereferenceable resources by means a client can attempt to dereference; 
     *  however, the received responses should still be verified.</p>
     */
    public static final Resource Resource = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Resource" );
    
    /** <p>States that the base Uri should be established using RFC 3986 reference resolution 
     *  algorithm specified in section 5.</p>
     */
    public static final Resource Rfc3986 = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Rfc3986" );
    
    /** <p>Additional information about a status code that might be returned.</p> */
    public static final Resource Status = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Status" );
    
    /** <p>A property known to be supported by a Hydra class.</p> */
    public static final Resource SupportedProperty = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#SupportedProperty" );
    
    /** <p>A templated link.</p> */
    public static final Resource TemplatedLink = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#TemplatedLink" );
    
    /** <p>A representation specifies how to serialize variable values into strings.</p> */
    public static final Resource VariableRepresentation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#VariableRepresentation" );
    
    /** <p>A link to the API documentation</p> */
    public static final Resource apiDocumentation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#apiDocumentation" );
    
    /** <p>Collections somehow related to this resource.</p> */
    public static final Resource collection = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#collection" );
    
    /** <p>A link to main entry point of the Web API</p> */
    public static final Resource entrypoint = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#entrypoint" );
    
    /** <p>The information expected by the Web API.</p> */
    public static final Resource expects = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#expects" );
    
    /** <p>The first resource of an interlinked set of resources.</p> */
    public static final Resource first = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#first" );
    
    /** <p>The last resource of an interlinked set of resources.</p> */
    public static final Resource last = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#last" );
    
    /** <p>A member of the collection</p> */
    public static final Resource member = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#member" );
    
    /** <p>The resource following the current instance in an interlinked set of resources.</p> */
    public static final Resource next = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#next" );
    
    /** <p>An operation supported by the Hydra resource</p> */
    public static final Resource operation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#operation" );
    
    /** <p>A status that might be returned by the Web API (other statuses should be expected 
     *  and properly handled as well)</p>
     */
    public static final Resource possibleStatus = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#possibleStatus" );
    
    /** <p>The resource preceding the current instance in an interlinked set of resources.</p> */
    public static final Resource previous = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#previous" );
    
    /** <p>The information returned by the Web API on success</p> */
    public static final Resource returns = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#returns" );
    
    /** <p>A IRI template that can be used to query a collection.</p> */
    public static final Resource search = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#search" );
    
    /** <p>A class known to be supported by the Web API</p> */
    public static final Resource supportedClass = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#supportedClass" );
    
    /** <p>An operation supported by instances of the specific Hydra class, or the target 
     *  of the Hydra link, or IRI template.</p>
     */
    public static final Resource supportedOperation = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#supportedOperation" );
    
    /** <p>The properties known to be supported by a Hydra class</p> */
    public static final Resource supportedProperty = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#supportedProperty" );
    
    /** <p>A specific view of a resource.</p> */
    public static final Resource view = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#view" );
    
    /** <p>An IRI template as defined by RFC6570.</p> */
    public static final Resource Rfc6570Template = M_MODEL.createResource( "http://www.w3.org/ns/hydra/core#Rfc6570Template" );
    
}
