package se.liu.ida.hefquin.vocabulary;

/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from hydra.ttl 
 * @author Auto-generated by schemagen on 27 Jan 2026 13:31 
 */
public class HydraVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/hydra/core#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>A variable-to-property mapping of the IRI template.</p> */
    public static final Property mapping = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#mapping" );
    
    /** <p>True if the property is required, false otherwise.</p> */
    public static final Property required = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#required" );
    
    /** <p>A templated string with placeholders. The literal's datatype indicates the 
     *  template syntax; if not specified, hydra:Rfc6570Template is assumed.</p>
     */
    public static final Property template = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#template" );
    
    /** <p>An IRI template variable</p> */
    public static final Property variable = M_MODEL.createProperty( "http://www.w3.org/ns/hydra/core#variable" );
    
}
