package se.liu.ida.hefquin.vocabulary;

/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from wotsec.ttl 
 * @author Auto-generated by schemagen on 09 Jul 2026 07:16 
 */
public class WoTSecVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://www.w3.org/2019/wot/security#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.0.1";
    
    /** <p>Encoding, encryption, or digest algorithm.</p> */
    public static final Property alg = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#alg" );
    
    /** <p>Array of two or more strings identifying other named security scheme definitions, 
     *  all of which must be satisfied for access.</p>
     */
    public static final Property allOf = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#allOf" );
    
    /** <p>Specifies the location of security authentication information.</p> */
    public static final Property apikeyIn = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#apikeyIn" );
    
    /** <p>URI of the authorization server.</p> */
    public static final Property authorization = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#authorization" );
    
    /** <p>Authorization flow.</p> */
    public static final Property flow = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#flow" );
    
    /** <p>Specifies format of security authentication information.</p> */
    public static final Property format = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#format" );
    
    /** <p>Identifier providing information which can be used for selection or confirmation.</p> */
    public static final Property identity = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#identity" );
    
    /** <p>Specifies the location of security authentication information.</p> */
    public static final Property in = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#in" );
    
    /** <p>Name for query, header, cookie, or uri parameters.</p> */
    public static final Property name = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#name" );
    
    /** <p>Array of two or more strings identifying other named security scheme definitions, 
     *  any one of which, when satisfied, will allow access. Only one may be chosen 
     *  for use.</p>
     */
    public static final Property oneOf = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#oneOf" );
    
    /** <p>URI of the proxy server this security configuration provides access to. If 
     *  not given, the corresponding security configuration is for the endpoint. &lt;br/&gt;This 
     *  feature is at risk.</p>
     */
    public static final Property proxy = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#proxy" );
    
    /** <p>Quality of protection. &lt;br/&gt;This feature is at risk.</p> */
    public static final Property qop = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#qop" );
    
    /** <p>URI of the refresh server.</p> */
    public static final Property refresh = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#refresh" );
    
    /** <p>Set of authorization scope identifiers provided as an array. These are provided 
     *  in tokens returned by an authorization server and associated with forms in 
     *  order to identify what resources a client may access and how. The values associated 
     *  with a form should be chosen from those defined in an &lt;code&gt;OAuth2SecurityScheme&lt;/code&gt; 
     *  active on that form. &lt;br/&gt;This feature is at risk.</p>
     */
    public static final Property scopes = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#scopes" );
    
    /** <p>URI of the token server.</p> */
    public static final Property token = M_MODEL.createProperty( "https://www.w3.org/2019/wot/security#token" );
    
    /** <p>API key authentication security configuration identified by the term &lt;code&gt;apikey&lt;/code&gt; 
     *  (i.e., &lt;code&gt;"scheme": "apikey"&lt;/code&gt;). This scheme is to be 
     *  used when the access token is opaque, for example when a key in a proprietary 
     *  format is provided by a cloud service provider. In this case the key may not 
     *  be using a standard token format. This scheme indicates that the key provided 
     *  by the service provider needs to be supplied as part of service requests using 
     *  the mechanism indicated by the &lt;code&gt;"in"&lt;/code&gt; field.</p>
     */
    public static final Resource APIKeySecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#APIKeySecurityScheme" );
    
    /** <p>An automatic authentication security configuration identified by the term 
     *  &lt;code&gt;auto&lt;/code&gt; (i.e., &lt;code&gt;"scheme": "auto"&lt;/code&gt;). 
     *  This scheme indicates that the security parameters are going to be negotiated 
     *  by the underlying protocols at runtime, subject to the respective specifications 
     *  for the protocol (e.g. [[!RFC8288]] for Basic Authentication when using HTTP).</p>
     */
    public static final Resource AutoSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#AutoSecurityScheme" );
    
    /** <p>Basic authentication security configuration identified by the term &lt;code&gt;basic&lt;/code&gt; 
     *  (i.e., &lt;code&gt;"scheme": "basic"&lt;/code&gt;), using an unencrypted username 
     *  and password.</p>
     */
    public static final Resource BasicSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#BasicSecurityScheme" );
    
    /** <p>Bearer token authentication security configuration identified by the term 
     *  &lt;code&gt;bearer&lt;/code&gt; (i.e., &lt;code&gt;"scheme": "bearer"&lt;/code&gt;). 
     *  This scheme is intended for situations where bearer tokens are used independently 
     *  of OAuth2. If the &lt;code&gt;oauth2&lt;/code&gt; scheme is specified it is 
     *  not generally necessary to specify this scheme as well as it is implied. For 
     *  &lt;code&gt;format&lt;/code&gt;, the value &lt;code&gt;jwt&lt;/code&gt; indicates 
     *  conformance with RFC7519, &lt;code&gt;jws&lt;/code&gt; indicates conformance 
     *  with RFC7797, &lt;code&gt;cwt&lt;/code&gt; indicates conformance with RFC8392, 
     *  and &lt;code&gt;jwe&lt;/code&gt; indicates conformance with !RFC7516, with 
     *  values for &lt;code&gt;alg&lt;/code&gt; interpreted consistently with those 
     *  standards. &lt;span class="rfc2119-assertion" id="td-security-bearer-format-extensions"&gt;Other 
     *  formats and algorithms for bearer tokens MAY be specified in vocabulary extensions.&lt;/span&gt;</p>
     */
    public static final Resource BearerSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#BearerSecurityScheme" );
    
    /** <p>&lt;p&gt;A combination of other security schemes identified by the &lt;a&gt;Vocabulary 
     *  Term&lt;/a&gt; &lt;code&gt;combo&lt;/code&gt; (i.e., &lt;code&gt;"scheme": 
     *  "combo"&lt;/code&gt;). Elements of this scheme define various ways in which 
     *  other named schemes defined in &lt;code&gt;securityDefinitions&lt;/code&gt;, 
     *  including other &lt;a href="#ComboSecurityScheme"&gt;&lt;code&gt;ComboSecurityScheme&lt;/code&gt;&lt;/a&gt; 
     *  definitions, are to be combined to create a new scheme definition. &lt;span 
     *  class="rfc2119-assertion" id="td-security-combo-exclusive-oneof-or-allof"&gt;Exactly 
     *  one of either &lt;code&gt;oneOf&lt;/code&gt; or &lt;code&gt;allOf&lt;/code&gt; 
     *  MUST be included.&lt;/span&gt; &lt;!-- Redundant, table states "two or more" 
     *  already &lt;scan class="rfc2119-assertion"&gt;The array given as a value associated 
     *  with either &lt;code&gt;oneOf&lt;/code&gt; or &lt;code&gt;allOf&lt;/code&gt; 
     *  MUST have at least two elements.&lt;/scan&gt; --&gt; Only security scheme 
     *  definitions which can be used together can be combined with &lt;code&gt;allOf&lt;/code&gt;. 
     *  For example, it is not possible in general to combine different OAuth 2.0 
     *  flows together using &lt;code&gt;allOf&lt;/code&gt; unless one applies to 
     *  a proxy and one to the endpoint. Note that when multiple named security scheme 
     *  definitions are listed in a &lt;code&gt;security&lt;/code&gt; field the same 
     *  semantics apply as in an &lt;code&gt;allOf&lt;/code&gt; combination (and the 
     *  same limitations on allowable combinations). The &lt;code&gt;oneOf&lt;/code&gt; 
     *  combination is equivalent to using different security schemes on forms that 
     *  are otherwise identical. In this sense a &lt;code&gt;oneOf&lt;/code&gt; scheme 
     *  is not an essential feature but it does avoid redundancy in such cases.&lt;/p&gt;</p>
     */
    public static final Resource ComboSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#ComboSecurityScheme" );
    
    /** <p>Digest authentication security configuration identified by the term &lt;code&gt;digest&lt;/code&gt; 
     *  (i.e., &lt;code&gt;"scheme": "digest"&lt;/code&gt;). This scheme is similar 
     *  to basic authentication but with added features to avoid man-in-the-middle 
     *  attacks.</p>
     */
    public static final Resource DigestSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#DigestSecurityScheme" );
    
    /** <p>A security configuration corresponding to identified by the term &lt;code&gt;nosec&lt;/code&gt; 
     *  (i.e., &lt;code&gt;"scheme": "nosec"&lt;/code&gt;), indicating there is no 
     *  authentication or other mechanism required to access the resource.</p>
     */
    public static final Resource NoSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#NoSecurityScheme" );
    
    /** <p>&lt;p&gt;OAuth 2.0 authentication security configuration for systems conformant 
     *  with [[!RFC6749]] and [[!RFC8252]], &lt;!-- and (for the &lt;code&gt;device&lt;/code&gt; 
     *  flow) [[!RFC8628]],--&gt; identified by the &lt;a&gt;Vocabulary Term&lt;/a&gt; 
     *  &lt;code&gt;oauth2&lt;/code&gt; (i.e., &lt;code&gt;"scheme": "oauth2"&lt;/code&gt;). 
     *  &lt;span class="rfc2119-assertion" id="td-security-oauth2-code-flow"&gt;For 
     *  the &lt;code&gt;code&lt;/code&gt; flow both &lt;code&gt;authorization&lt;/code&gt; 
     *  and &lt;code&gt;token&lt;/code&gt; MUST be included.&lt;/span&gt; &lt;span 
     *  class="rfc2119-assertion" id="td-security-oauth2-client-flow"&gt;For the &lt;code&gt;client&lt;/code&gt; 
     *  flow &lt;code&gt;token&lt;/code&gt; MUST be included.&lt;/span&gt; &lt;span 
     *  class="rfc2119-assertion" id="td-security-oauth2-client-flow-no-auth"&gt;For 
     *  the &lt;code&gt;client&lt;/code&gt; flow &lt;code&gt;authorization&lt;/code&gt; 
     *  MUST NOT be included.&lt;/span&gt; &lt;!-- &lt;span class="rfc2119-assertion" 
     *  id="td-security-oauth2-device-flow"&gt;For the &lt;code&gt;device&lt;/code&gt; 
     *  flow both &lt;code&gt;authorization&lt;/code&gt; and &lt;code&gt;token&lt;/code&gt; 
     *  MUST be included.&lt;/span&gt; In the case of the &lt;code&gt;device&lt;/code&gt; 
     *  flow the value provided for &lt;code&gt;authorization&lt;/code&gt; refers 
     *  to the device authorization endpoint defined in [[!RFC8628]].--&gt; The mandatory 
     *  elements for each flow are summarized in the following table: &lt;table class="def"&gt; 
     *  &lt;tr&gt;&lt;th&gt;Element&lt;/th&gt;&lt;th&gt;&lt;code&gt;code&lt;/code&gt;&lt;/th&gt;&lt;th&gt;&lt;code&gt;client&lt;/code&gt;&lt;/th&gt;&lt;!-- 
     *  &lt;th&gt;&lt;code&gt;device&lt;/code&gt;&lt;/th&gt; --&gt;&lt;/tr&gt; &lt;tr&gt;&lt;td&gt;&lt;code&gt;authorization&lt;/code&gt;&lt;/td&gt;&lt;td&gt;mandatory&lt;/td&gt;&lt;td&gt;omit&lt;/td&gt;&lt;!-- 
     *  &lt;td&gt;mandatory; refers to device authorization endpoint&lt;/td&gt; --&gt;&lt;/tr&gt; 
     *  &lt;tr&gt;&lt;td&gt;&lt;code&gt;token&lt;/code&gt;&lt;/td&gt;&lt;td&gt;mandatory&lt;/td&gt;&lt;td&gt;mandatory&lt;/td&gt;&lt;!-- 
     *  &lt;td&gt;mandatory&lt;/td&gt; --&gt;&lt;/tr&gt; &lt;tr&gt;&lt;td&gt;&lt;code&gt;refresh&lt;/code&gt;&lt;/td&gt;&lt;td&gt;optional&lt;/td&gt;&lt;td&gt;optional&lt;/td&gt;&lt;!-- 
     *  &lt;td&gt;optional&lt;/td&gt; --&gt;&lt;/tr&gt; &lt;/table&gt; &lt;/p&gt; 
     *  &lt;!-- &lt;p class="ednote"&gt; Note that the table below lists these elements 
     *  as "optional". In fact whether they are mandatory or not depends on the flow. 
     *  The &lt;code&gt;token&lt;/code&gt; element is listed as optional even though 
     *  it is mandatory for all predefined flows since it might not be mandatory for 
     *  some flows defined in an extension. We should investigate whether there is 
     *  a better way to express these "variant record" constraints.&lt;/p&gt;&lt;p&gt;If 
     *  multiple flows are available (for example, multiple OAuth 2.0 security schemes 
     *  with different flows are given for a &lt;code&gt;Form&lt;/code&gt;) then only 
     *  one may be selected for use by a &lt;a&gt;Consumer&lt;/a&gt;. &lt;span class="rfc2119-assertion" 
     *  id="td-security-oauth2-other-flows"&gt;If an OAuth 2.0 flow other than &lt;code&gt;code&lt;/code&gt;, 
     *  &lt;code&gt;client&lt;/code&gt; or &lt;code&gt;device&lt;/code&gt; needs to 
     *  be specified an extension vocabulary MUST be used.&lt;/span&gt; This includes 
     *  the &lt;code&gt;password&lt;/code&gt; and &lt;code&gt;implicit&lt;/code&gt; 
     *  flows, which are no longer considered best practice [[WOT-SECURITY-GUIDELINES]]. 
     *  This also applies to flows that are similar at the protocol level but do not 
     *  exactly follow the OAuth 2.0 specification, for example by automating grants 
     *  rather than invoking a user agent to interact with a human resource owner. 
     *  If no &lt;code&gt;scopes&lt;/code&gt; are defined in the &lt;code&gt;SecurityScheme&lt;/code&gt; 
     *  then they are considered to be empty.&lt;/p&gt; &lt;p class="ednote"&gt;The 
     *  device authorization endpoint technically uses a different protocol than the 
     *  authorization endpoint used by other flows, and it might be possible for a 
     *  developer to confuse the two. However, since the &lt;code&gt;device&lt;/code&gt; 
     *  flow does not use the regular authorization endpoint there should be no ambiguity. 
     *  We are considering however an alternative design where there is a separate 
     *  element, &lt;code&gt;device_authorization&lt;/code&gt;, which MUST be included 
     *  for the &lt;code&gt;device&lt;/code&gt; flow (and then the regular authorization 
     *  endpoint then MUST NOT be used).&lt;/p&gt; --&gt;</p>
     */
    public static final Resource OAuth2SecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#OAuth2SecurityScheme" );
    
    /** <p>Pre-shared key authentication security configuration identified by the term 
     *  &lt;code&gt;psk&lt;/code&gt; (i.e., &lt;code&gt;"scheme": "psk"&lt;/code&gt;). 
     *  This is meant to identify that a standard is used for pre-shared keys such 
     *  as TLS-PSK [[rfc4279]], and that the ciphersuite used for keys will be established 
     *  during protocol negotiation.</p>
     */
    public static final Resource PSKSecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#PSKSecurityScheme" );
    
    public static final Resource SecurityScheme = M_MODEL.createResource( "https://www.w3.org/2019/wot/security#SecurityScheme" );
    
}
