package se.liu.ida.hefquin.vocabulary;

/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from https://www.w3.org/2019/wot/td 
 * @author Auto-generated by schemagen on 09 Jul 2026 07:19 
 */
public class WoTTDVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://www.w3.org/2019/wot/td#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.9.0";
    
    /** <p>Define the base URI that is used for all relative URI references throughout 
     *  a TD document. In TD instances, all relative URIs are resolved relative to 
     *  the base URI using the algorithm defined in [RFC3986]. base does not affect 
     *  the URIs used in @context and the IRIs used within Linked Data [LINKED-DATA] 
     *  graphs that are relevant when semantic processing is applied to TD instances.</p>
     */
    public static final Property baseURI = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#baseURI" );
    
    /** <p>A Thing may define abstract security schemes, used to configure the secure 
     *  access of (a set of) affordance(s).</p>
     */
    public static final Property definesSecurityScheme = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#definesSecurityScheme" );
    
    /** <p>description of the TD element (Thing, interaction affordance, security scheme 
     *  or data schema)</p>
     */
    public static final Property description = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#description" );
    
    /** <p>description of the TD element (Thing, interaction affordance, security scheme 
     *  or data schema) with language tag. By convention, a language tag must be added 
     *  to the object of 'descriptionInLanguage' triples. Otherwise, use 'description'.</p>
     */
    public static final Property descriptionInLanguage = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#descriptionInLanguage" );
    
    /** <p>Indicates the WoT Profile mechanisms followed by this Thing Description and 
     *  the corresponding Thing implementation.</p>
     */
    public static final Property followsProfile = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#followsProfile" );
    
    /** <p>All Action-based interaction affordance of the Thing.</p> */
    public static final Property hasActionAffordance = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasActionAffordance" );
    
    /** <p>Defines any data that needs to be passed to cancel a subscription, e.g., a 
     *  specific message to remove a Webhook</p>
     */
    public static final Property hasCancellationSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasCancellationSchema" );
    
    /** <p>All Event-based interaction affordance of the Thing.</p> */
    public static final Property hasEventAffordance = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasEventAffordance" );
    
    /** <p>Set of form hypermedia controls that describe how an operation can be performed. 
     *  Forms are serializations of Protocol Bindings. The array cannot be empty</p>
     */
    public static final Property hasForm = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasForm" );
    
    /** <p>Used to define the input data schema of the action.</p> */
    public static final Property hasInputSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasInputSchema" );
    
    /** <p>Instantiation, as used here, is a form of non-symmetric equivalence between 
     *  a scheme and a configuration: whatever statement on the scheme is also true 
     *  of the configuration but not vice-versa.</p>
     */
    public static final Property hasInstanceConfiguration = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasInstanceConfiguration" );
    
    /** <p>Offers an affordance to interact with the Thing</p> */
    public static final Property hasInteractionAffordance = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasInteractionAffordance" );
    
    /** <p>Provides Web links to arbitrary resources that relate to the specified Thing 
     *  Description.</p>
     */
    public static final Property hasLink = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasLink" );
    
    /** <p>Defines the data schema of the Event response messages sent by the consumer 
     *  in a response to a data message.</p>
     */
    public static final Property hasNotificationResponseSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasNotificationResponseSchema" );
    
    /** <p>Defines the data schema of the Event instance messages pushed by the Thing.</p> */
    public static final Property hasNotificationSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasNotificationSchema" );
    
    /** <p>Used to define the output data schema of the action.</p> */
    public static final Property hasOutputSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasOutputSchema" );
    
    /** <p>All Property-based interaction affordance of the Thing.</p> */
    public static final Property hasPropertyAffordance = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasPropertyAffordance" );
    
    /** <p>A security configuration is a a security scheme applied to a (set of) affordance(s).</p> */
    public static final Property hasSecurityConfiguration = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasSecurityConfiguration" );
    
    /** <p>Defines data that needs to be passed upon subscription, e.g., filters or message 
     *  format for setting up Webhooks.</p>
     */
    public static final Property hasSubscriptionSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasSubscriptionSchema" );
    
    /** <p>Define URI template variables according to [[RFC6570]] as collection based 
     *  on schema specifications. The individual variables DataSchema cannot be an 
     *  ObjectSchema or an ArraySchema.</p>
     */
    public static final Property hasUriTemplateSchema = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#hasUriTemplateSchema" );
    
    /** <p>Provides a version identicator of this TD instance.</p> */
    public static final Property instance = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#instance" );
    
    /** <p>Indicates whether the action is idempotent (=true) or not. Informs whether 
     *  the action can be called repeatedly with the same result, if present, based 
     *  on the same input.</p>
     */
    public static final Property isIdempotent = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#isIdempotent" );
    
    /** <p>A hint that indicates whether Servients hosting the Thing and Intermediaries 
     *  should provide a Protocol Binding that supports the &lt;code&gt;observeproperty&lt;/code&gt; 
     *  and &lt;code&gt;unobserveproperty&lt;/code&gt; operations for this Property.</p>
     */
    public static final Property isObservable = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#isObservable" );
    
    /** <p>Signals if the action is safe (=true) or not. Used to signal if there is no 
     *  internal state (cf. resource state) is changed when invoking an Action. In 
     *  that case responses can be cached as example.</p>
     */
    public static final Property isSafe = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#isSafe" );
    
    /** <p>Indicates whether the action is synchronous (=true) or not. A synchronous 
     *  action means that the response of action contains all the information about 
     *  the result of the action and no further querying about the status of the action 
     *  is needed. Lack of this keyword means that no claim on the synchronicity of 
     *  the action can be made.</p>
     */
    public static final Property isSynchronous = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#isSynchronous" );
    
    /** <p>Provides a version indicator of the underlying TM.</p> */
    public static final Property model = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#model" );
    
    /** <p>Indexing property to store entity names when serializing them in a JSON-LD 
     *  @index container.</p>
     */
    public static final Property name = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#name" );
    
    /** <p>title of the TD element (Thing, interaction affordance or data schema)</p> */
    public static final Property title = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#title" );
    
    /** <p>title of the TD element (Thing, interaction affordance or data schema) with 
     *  language tag. By convention, a language tag must be added to the object of 
     *  'titleInLanguage' triples. Otherwise, use 'title'.</p>
     */
    public static final Property titleInLanguage = M_MODEL.createProperty( "https://www.w3.org/2019/wot/td#titleInLanguage" );
    
    /** <p>An Interaction Affordance that allows to invoke a function of the Thing, which 
     *  manipulates state (e.g., toggling a lamp on or off) or triggers a process 
     *  on the Thing (e.g., dim a lamp over time).</p>
     */
    public static final Resource ActionAffordance = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#ActionAffordance" );
    
    /** <p>An Interaction Affordance that describes an event source, which asynchronously 
     *  pushes event data to Consumers (e.g., overheating alerts).</p>
     */
    public static final Resource EventAffordance = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#EventAffordance" );
    
    /** <p>Metadata of a Thing that shows the possible choices to Consumers, thereby 
     *  suggesting how Consumers may interact with the Thing. There are many types 
     *  of potential affordances, but W3C WoT defines three types of Interaction Affordances: 
     *  Properties, Actions, and Events.</p>
     */
    public static final Resource InteractionAffordance = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#InteractionAffordance" );
    
    /** <p>Enumeration of well-known operation types necessary to implement the WoT interaction 
     *  model</p>
     */
    public static final Resource OperationType = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#OperationType" );
    
    /** <p>An Interaction Affordance that exposes state of the Thing. This state can 
     *  then be retrieved (read) and/or updated (write). Things can also choose to 
     *  make Properties observable by pushing the new state after a change.</p>
     */
    public static final Resource PropertyAffordance = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#PropertyAffordance" );
    
    /** <p>An abstraction of a physical or a virtual entity whose metadata and interfaces 
     *  are described by a WoT Thing Description, whereas a virtual entity is the 
     *  composition of one or more Things.</p>
     */
    public static final Resource Thing = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#Thing" );
    
    /** <p>Operation type of forms used to cancel an action</p> */
    public static final Resource cancelAction = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#cancelAction" );
    
    /** <p>Operation type of forms used to read a property value</p> */
    public static final Resource invokeAction = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#invokeAction" );
    
    /** <p>Operation type of forms used to observe all property values</p> */
    public static final Resource observeAllProperties = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#observeAllProperties" );
    
    /** <p>Operation type of forms used to observe a property value</p> */
    public static final Resource observeProperty = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#observeProperty" );
    
    /** <p>Operation type of forms used to query the status of an action</p> */
    public static final Resource queryAction = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#queryAction" );
    
    /** <p>Operation type of forms used to query the status of all actions</p> */
    public static final Resource queryAllActions = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#queryAllActions" );
    
    /** <p>Operation type of forms used to read all property values</p> */
    public static final Resource readAllProperties = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#readAllProperties" );
    
    /** <p>Operation type of forms used to read a property value</p> */
    public static final Resource readMultipleProperties = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#readMultipleProperties" );
    
    /** <p>Operation type of forms used to read a property value</p> */
    public static final Resource readProperty = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#readProperty" );
    
    /** <p>Operation type of forms used to subscribe to all event types</p> */
    public static final Resource subscribeAllEvents = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#subscribeAllEvents" );
    
    /** <p>Operation type of forms used to read a property value</p> */
    public static final Resource subscribeEvent = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#subscribeEvent" );
    
    /** <p>Operation type of forms used to unobserve all property value</p> */
    public static final Resource unobserveAllProperties = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#unobserveAllProperties" );
    
    /** <p>Operation type of forms used to unobserve a property value</p> */
    public static final Resource unobserveProperty = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#unobserveProperty" );
    
    /** <p>Operation type of forms used to unsubscribe from all event types</p> */
    public static final Resource unsubscribeAllEvents = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#unsubscribeAllEvents" );
    
    /** <p>Operation type of forms used to read a property value</p> */
    public static final Resource unsubscribeEvent = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#unsubscribeEvent" );
    
    /** <p>Operation type of forms used to read a property value</p> */
    public static final Resource writeAllProperties = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#writeAllProperties" );
    
    /** <p>Operation type of forms used to write a property value</p> */
    public static final Resource writeMultipleProperties = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#writeMultipleProperties" );
    
    /** <p>Operation type of forms used to write a property value</p> */
    public static final Resource writeProperty = M_MODEL.createResource( "https://www.w3.org/2019/wot/td#writeProperty" );
    
}
