SELECT DISTINCT ?drug ?melt WHERE {
  VALUES ( ?s1 ?s2 ) {
    ( <%s> UNDEF )
  }
  {
    SERVICE ?s1 { ?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/meltingPoint> ?melt . }
  }
  # UNION # extra empty mapping
  {
    SERVICE ?s2 { ?drug <http://dbpedia.org/ontology/Drug/meltingPoint> ?melt . }
  }
}