SELECT DISTINCT ?predicate ?object WHERE {
  VALUES ( ?s1 ?s2 ?s3 ) {
    ( <%s> UNDEF UNDEF )
    ( UNDEF <%s> <%s> )
  }
  {
    SERVICE ?s1 { <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00201> ?predicate ?object . }
  }
  # UNION # extra empty mapping
  {
    SERVICE ?s2 { <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00201> <http://www.w3.org/2002/07/owl#sameAs> ?caff . }
    SERVICE ?s3 { ?caff ?predicate ?object . }
  } 
}