SELECT DISTINCT ?drugDesc ?cpd ?equation WHERE {
  VALUES ( ?s1 ?s2 ?s3 ?s4 ?s5 ?s6 ?s7 ) {
    ( <%s> <%s> <%s> <%s> <%s> <%s> <%s> )
  }
  SERVICE ?s1 { ?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/drugCategory> <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugcategory/cathartics> . }
  SERVICE ?s2 { ?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/keggCompoundId> ?cpd . }
  SERVICE ?s3 { ?drug <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/description> ?drugDesc . }
  SERVICE ?s4 { ?enzyme <http://bio2rdf.org/ns/kegg#xSubstrate> ?cpd . }
  SERVICE ?s5 { ?enzyme <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://bio2rdf.org/ns/kegg#Enzyme> . }
  SERVICE ?s6 { ?reaction <http://bio2rdf.org/ns/kegg#xEnzyme> ?enzyme . }
  SERVICE ?s7 { ?reaction <http://bio2rdf.org/ns/kegg#equation> ?equation .  }
}