package se.liu.ida.hefquin.rml.vocabulary;

/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from https://kg-construct.github.io/rml-resources/ontology.ttl 
 * @author Auto-generated by schemagen on 29 Nov 2025 21:54 
 */
public class RMLVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://w3id.org/rml/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.1.0";
    
    /** <p>Indicates the behavior of a GatherMap in case rml:gather does not yield any 
     *  element</p>
     */
    public static final Property allowEmptyListAndContainer = M_MODEL.createProperty( "http://w3id.org/rml/allowEmptyListAndContainer" );
    
    /** <p>Indicates the base IRI of the RDF graph to be created with a triples map.</p> */
    public static final Property baseIRI = M_MODEL.createProperty( "http://w3id.org/rml/baseIRI" );
    
    /** <p>Names a source record in the child source of a join.</p> */
    public static final Property child = M_MODEL.createProperty( "http://w3id.org/rml/child" );
    
    /** <p>Names a child map in the child source of a join.</p> */
    public static final Property childMap = M_MODEL.createProperty( "http://w3id.org/rml/childMap" );
    
    /** <p>The subject value generated for a logical source record will be asserted as 
     *  an instance of this RDFS class.</p>
     */
    public static final Property class_ = M_MODEL.createProperty( "http://w3id.org/rml/class" );
    
    /** <p>Defines the compression format of a Source or Target.</p> */
    public static final Property compression = M_MODEL.createProperty( "http://w3id.org/rml/compression" );
    
    /** <p>Specifies the datatype of the object component for the generated triple.</p> */
    public static final Property datatype = M_MODEL.createProperty( "http://w3id.org/rml/datatype" );
    
    /** <p>A DatatypetMap element to generate the datatype component of the object component 
     *  from a logical source record.</p>
     */
    public static final Property datatypeMap = M_MODEL.createProperty( "http://w3id.org/rml/datatypeMap" );
    
    /** <p>Defines the encoding format of a Source or Target.</p> */
    public static final Property encoding = M_MODEL.createProperty( "http://w3id.org/rml/encoding" );
    
    /** <p>A field of the logical view.</p> */
    public static final Property field = M_MODEL.createProperty( "http://w3id.org/rml/field" );
    
    /** <p>The name of the field.</p> */
    public static final Property fieldName = M_MODEL.createProperty( "http://w3id.org/rml/fieldName" );
    
    /** <p>Specifies a data transformation function.</p> */
    public static final Property function = M_MODEL.createProperty( "http://w3id.org/rml/function" );
    
    /** <p>Denotes the execution of a function with its required input parameters and 
     *  values.</p>
     */
    public static final Property functionExecution = M_MODEL.createProperty( "http://w3id.org/rml/functionExecution" );
    
    /** <p>A Function Map element to generate the data transformation function.</p> */
    public static final Property functionMap = M_MODEL.createProperty( "http://w3id.org/rml/functionMap" );
    
    /** <p>Specifies where the terms of a collection or container come from.</p> */
    public static final Property gather = M_MODEL.createProperty( "http://w3id.org/rml/gather" );
    
    /** <p>Relates a GatherMap with the desired result type of collection or container.</p> */
    public static final Property gatherAs = M_MODEL.createProperty( "http://w3id.org/rml/gatherAs" );
    
    /** <p>An IRI reference for use as the graph name of all triples generated with the 
     *  SubjectMap or PredicateObjectMap.</p>
     */
    public static final Property graph = M_MODEL.createProperty( "http://w3id.org/rml/graph" );
    
    /** <p>Specifies a GraphMap. When used with a SubjectMap element, all the RDF triples 
     *  generated from a logical row will be stored in the specified named graph. 
     *  Otherwise, the RDF triple generated using the (predicate, object) pair will 
     *  be stored in the specified named graph.</p>
     */
    public static final Property graphMap = M_MODEL.createProperty( "http://w3id.org/rml/graphMap" );
    
    /** <p>An inner join of the logical view.</p> */
    public static final Property innerJoin = M_MODEL.createProperty( "http://w3id.org/rml/innerJoin" );
    
    /** <p>Specifies the Input element of a Function Map.</p> */
    public static final Property input = M_MODEL.createProperty( "http://w3id.org/rml/input" );
    
    /** <p>Specifies the value of a parameter of a function.</p> */
    public static final Property inputValue = M_MODEL.createProperty( "http://w3id.org/rml/inputValue" );
    
    /** <p>A Value map element to generate the value of a parameter of a function.</p> */
    public static final Property inputValueMap = M_MODEL.createProperty( "http://w3id.org/rml/inputValueMap" );
    
    /** <p>An expression qualified according to the reference formulation that defines 
     *  a sequence of logical iterations on the data source.</p>
     */
    public static final Property iterator = M_MODEL.createProperty( "http://w3id.org/rml/iterator" );
    
    /** <p>Specifies the join condition for joining the child logical source with the 
     *  parent logical source of the foreign key constraint.</p>
     */
    public static final Property joinCondition = M_MODEL.createProperty( "http://w3id.org/rml/joinCondition" );
    
    /** <p>Specified the language for the object component for the generated triple.</p> */
    public static final Property language = M_MODEL.createProperty( "http://w3id.org/rml/language" );
    
    /** <p>A LanguagetMap element to generate the language tag of the object component 
     *  from a logical source record.</p>
     */
    public static final Property languageMap = M_MODEL.createProperty( "http://w3id.org/rml/languageMap" );
    
    /** <p>A left join of the logical view.</p> */
    public static final Property leftJoin = M_MODEL.createProperty( "http://w3id.org/rml/leftJoin" );
    
    /** <p>Represents the logical source to be mapped.</p> */
    public static final Property logicalSource = M_MODEL.createProperty( "http://w3id.org/rml/logicalSource" );
    
    /** <p>Represents the logical target to where triples are exported to.</p> */
    public static final Property logicalTarget = M_MODEL.createProperty( "http://w3id.org/rml/logicalTarget" );
    
    /** <p>A namespace for describing a XPath reference formulation.</p> */
    public static final Property namespace = M_MODEL.createProperty( "http://w3id.org/rml/namespace" );
    
    /** <p>Describes the prefix of a namespace.</p> */
    public static final Property namespacePrefix = M_MODEL.createProperty( "http://w3id.org/rml/namespacePrefix" );
    
    /** <p>Describes the URL of a namespace.</p> */
    public static final Property namespaceURL = M_MODEL.createProperty( "http://w3id.org/rml/namespaceURL" );
    
    /** <p>Describes which data values inside the source should be considered as NULL.</p> */
    public static final Property null_ = M_MODEL.createProperty( "http://w3id.org/rml/null" );
    
    /** <p>Specifies the object for the generated triple from the logical source record.</p> */
    public static final Property object = M_MODEL.createProperty( "http://w3id.org/rml/object" );
    
    /** <p>An ObjectMap element to generate the object component of the (predicate, object) 
     *  pair from a logical source record.</p>
     */
    public static final Property objectMap = M_MODEL.createProperty( "http://w3id.org/rml/objectMap" );
    
    /** <p>The property onFields specifies the fields in LogicalView that are involved 
     *  by the structural annotation. The semantics of this involvement depends on 
     *  the specific annotation.</p>
     */
    public static final Property onFields = M_MODEL.createProperty( "http://w3id.org/rml/onFields" );
    
    /** <p>Specifies the parameter of a function.</p> */
    public static final Property parameter = M_MODEL.createProperty( "http://w3id.org/rml/parameter" );
    
    /** <p>A Parameter Map element to generate the parameter of a function.</p> */
    public static final Property parameterMap = M_MODEL.createProperty( "http://w3id.org/rml/parameterMap" );
    
    /** <p>Names a source record in the parent source of a join.</p> */
    public static final Property parent = M_MODEL.createProperty( "http://w3id.org/rml/parent" );
    
    /** <p>The parent logical view of the logical view join.</p> */
    public static final Property parentLogicalView = M_MODEL.createProperty( "http://w3id.org/rml/parentLogicalView" );
    
    /** <p>Names a parent map in the parent source of a join.</p> */
    public static final Property parentMap = M_MODEL.createProperty( "http://w3id.org/rml/parentMap" );
    
    /** <p>Specifies the TriplesMap element corresponding to the parent logical source 
     *  of the foreign key constraint.</p>
     */
    public static final Property parentTriplesMap = M_MODEL.createProperty( "http://w3id.org/rml/parentTriplesMap" );
    
    /** <p>Denotes the path to a source or target resource.</p> */
    public static final Property path = M_MODEL.createProperty( "http://w3id.org/rml/path" );
    
    /** <p>Specifies the predicate for the generated triple from the logical source record.</p> */
    public static final Property predicate = M_MODEL.createProperty( "http://w3id.org/rml/predicate" );
    
    /** <p>A PredicateMap element to generate the predicate component of the (predicate, 
     *  object) pair from a logical source record.</p>
     */
    public static final Property predicateMap = M_MODEL.createProperty( "http://w3id.org/rml/predicateMap" );
    
    /** <p>A PredicateObjectMap element to generate (predicate, object) pair from a logical 
     *  source record.</p>
     */
    public static final Property predicateObjectMap = M_MODEL.createProperty( "http://w3id.org/rml/predicateObjectMap" );
    
    /** <p>An quoted TriplesMap element to generate a RDF-star triple as subject or object 
     *  or another triple from a logical source record.</p>
     */
    public static final Property quotedTriplesMap = M_MODEL.createProperty( "http://w3id.org/rml/quotedTriplesMap" );
    
    /** <p>A valid expression that selects values from the source data. The reference 
     *  should conform to the syntax rules/grammar of the specified Reference Formulation.</p>
     */
    public static final Property reference = M_MODEL.createProperty( "http://w3id.org/rml/reference" );
    
    /** <p>The reference formulation used to refer to extracts of the source data.</p> */
    public static final Property referenceFormulation = M_MODEL.createProperty( "http://w3id.org/rml/referenceFormulation" );
    
    /** <p>Specifies the return output of a function.</p> */
    public static final Property return_ = M_MODEL.createProperty( "http://w3id.org/rml/return" );
    
    /** <p>A Return Map element to generate the return output of a function.</p> */
    public static final Property returnMap = M_MODEL.createProperty( "http://w3id.org/rml/returnMap" );
    
    /** <p>Defines the root of the relative path.</p> */
    public static final Property root = M_MODEL.createProperty( "http://w3id.org/rml/root" );
    
    /** <p>Defines the serialization to generate the target output.</p> */
    public static final Property serialization = M_MODEL.createProperty( "http://w3id.org/rml/serialization" );
    
    /** <p>Defines the source that describe the input data.</p> */
    public static final Property source = M_MODEL.createProperty( "http://w3id.org/rml/source" );
    
    /** <p>A Strategy element to indicate how to perform an action (e.g. gather for collections 
     *  and containers, join).A Strategy element to indicate how to perform an action.</p>
     */
    public static final Property strategy = M_MODEL.createProperty( "http://w3id.org/rml/strategy" );
    
    /** <p>A structural annotation of the logical view.</p> */
    public static final Property structuralAnnotation = M_MODEL.createProperty( "http://w3id.org/rml/structuralAnnotation" );
    
    /** <p>An IRI reference for use as subject for all the RDF triples generated from 
     *  a logical source record.</p>
     */
    public static final Property subject = M_MODEL.createProperty( "http://w3id.org/rml/subject" );
    
    /** <p>A SubjectMap element to generate a subject from a logical source record.</p> */
    public static final Property subjectMap = M_MODEL.createProperty( "http://w3id.org/rml/subjectMap" );
    
    /** <p>Defines the target that describe the output data.</p> */
    public static final Property target = M_MODEL.createProperty( "http://w3id.org/rml/target" );
    
    /** <p>The property targetFields specifies the Fields target of the InclusionAnnotation.</p> */
    public static final Property targetFields = M_MODEL.createProperty( "http://w3id.org/rml/targetFields" );
    
    /** <p>The property targetFields specifies the Fields target of the InclusionAnnotation.</p> */
    public static final Property targetView = M_MODEL.createProperty( "http://w3id.org/rml/targetView" );
    
    /** <p>A template (format string) to specify how to generate a value for a expression 
     *  map, using one or more records from a logical source record.</p>
     */
    public static final Property template = M_MODEL.createProperty( "http://w3id.org/rml/template" );
    
    /** <p>A string indicating whether subject or object generated using the value from 
     *  a source record name specified should be an IRI/URI (safe or unsafe) reference, 
     *  blank node, or a literal.</p>
     */
    public static final Property termType = M_MODEL.createProperty( "http://w3id.org/rml/termType" );
    
    /** <p>The source of the logical view. This is the abstract logical source from which 
     *  the logical view is derived.</p>
     */
    public static final Property viewOn = M_MODEL.createProperty( "http://w3id.org/rml/viewOn" );
    
    /** <p>An iterable that can be associated with a triples map such that a data source 
     *  can be mapped to RDF triples.</p>
     */
    public static final Resource AbstractLogicalSource = M_MODEL.createResource( "http://w3id.org/rml/AbstractLogicalSource" );
    
    /** <p>A type of Triples Map that is quoted and asserted in the resulting graph.</p> */
    public static final Resource AssertedTriplesMap = M_MODEL.createResource( "http://w3id.org/rml/AssertedTriplesMap" );
    
    /** <p>Denotes a blank node, used with termType</p> */
    public static final Resource BlankNode = M_MODEL.createResource( "http://w3id.org/rml/BlankNode" );
    
    /** <p>Represents a child map</p> */
    public static final Resource ChildMap = M_MODEL.createResource( "http://w3id.org/rml/ChildMap" );
    
    /** <p>Represents file compression schemes.</p> */
    public static final Resource Compression = M_MODEL.createResource( "http://w3id.org/rml/Compression" );
    
    /** <p>Denotes the path to the current working directory of the RML processor.</p> */
    public static final Resource CurrentWorkingDirectory = M_MODEL.createResource( "http://w3id.org/rml/CurrentWorkingDirectory" );
    
    /** <p>Represents a datatype map</p> */
    public static final Resource DatatypeMap = M_MODEL.createResource( "http://w3id.org/rml/DatatypeMap" );
    
    /** <p>Represents encoding formats.</p> */
    public static final Resource Encoding = M_MODEL.createResource( "http://w3id.org/rml/Encoding" );
    
    /** <p>An expression field is an expression map that gives a name to an expression.</p> */
    public static final Resource ExpressionField = M_MODEL.createResource( "http://w3id.org/rml/ExpressionField" );
    
    /** <p>Represents an expression map</p> */
    public static final Resource ExpressionMap = M_MODEL.createResource( "http://w3id.org/rml/ExpressionMap" );
    
    /** <p>A field gives a name to data derived from the abstract logical source on which 
     *  a logical view is defined.</p>
     */
    public static final Resource Field = M_MODEL.createResource( "http://w3id.org/rml/Field" );
    
    /** <p>A foreign key annotation is analogous to the notion of foreign key constraint 
     *  in databases.</p>
     */
    public static final Resource ForeignKeyAnnotation = M_MODEL.createResource( "http://w3id.org/rml/ForeignKeyAnnotation" );
    
    /** <p>Represents a function execution.</p> */
    public static final Resource FunctionExecution = M_MODEL.createResource( "http://w3id.org/rml/FunctionExecution" );
    
    /** <p>Represents a function map.</p> */
    public static final Resource FunctionMap = M_MODEL.createResource( "http://w3id.org/rml/FunctionMap" );
    
    /** <p>Denotes a term map that generates a collection (rdf:List) or container (rdf:Bag, 
     *  rdf:Seq, rdf:Alt).</p>
     */
    public static final Resource GatherMap = M_MODEL.createResource( "http://w3id.org/rml/GatherMap" );
    
    /** <p>Represents a graph map.</p> */
    public static final Resource GraphMap = M_MODEL.createResource( "http://w3id.org/rml/GraphMap" );
    
    /** <p>Denotes an IRI, used with termType.</p> */
    public static final Resource IRI = M_MODEL.createResource( "http://w3id.org/rml/IRI" );
    
    /** <p>A IRI safe annotation indicates that the field content is IRI safe.</p> */
    public static final Resource IRISafeAnnotation = M_MODEL.createResource( "http://w3id.org/rml/IRISafeAnnotation" );
    
    /** <p>An inclusion dependency annotation is analogous to the notion of inclusion 
     *  dependency in databases.</p>
     */
    public static final Resource InclusionDependencyAnnotation = M_MODEL.createResource( "http://w3id.org/rml/InclusionDependencyAnnotation" );
    
    /** <p>Represents a input for an execution.</p> */
    public static final Resource Input = M_MODEL.createResource( "http://w3id.org/rml/Input" );
    
    /** <p>An abstract construct to describe data access and iteration for a data source.</p> */
    public static final Resource Iterable = M_MODEL.createResource( "http://w3id.org/rml/Iterable" );
    
    /** <p>An iterable field is an iterable that gives a name to a logical iteration.</p> */
    public static final Resource IterableField = M_MODEL.createResource( "http://w3id.org/rml/IterableField" );
    
    /** <p>Represents a join condition.</p> */
    public static final Resource Join = M_MODEL.createResource( "http://w3id.org/rml/Join" );
    
    /** <p>Represents a language map</p> */
    public static final Resource LanguageMap = M_MODEL.createResource( "http://w3id.org/rml/LanguageMap" );
    
    /** <p>Denotes a Literal, used with termType.</p> */
    public static final Resource Literal = M_MODEL.createResource( "http://w3id.org/rml/Literal" );
    
    /** <p>Denotes a logical source.</p> */
    public static final Resource LogicalSource = M_MODEL.createResource( "http://w3id.org/rml/LogicalSource" );
    
    /** <p>Denotes a logical target.</p> */
    public static final Resource LogicalTarget = M_MODEL.createResource( "http://w3id.org/rml/LogicalTarget" );
    
    /** <p>A logical view (rml:LogicalView) is a type of abstract logical source that 
     *  is derived from another abstract logical source by defining fields with data 
     *  from said abstract logical source.</p>
     */
    public static final Resource LogicalView = M_MODEL.createResource( "http://w3id.org/rml/LogicalView" );
    
    /** <p>A logical view join is an operation that adapts the logical iterations of 
     *  one logical view (the child logical view) with fields from another logical 
     *  view (the parent logical view).</p>
     */
    public static final Resource LogicalViewJoin = M_MODEL.createResource( "http://w3id.org/rml/LogicalViewJoin" );
    
    /** <p>Denotes the path to the location of the RML mapping.</p> */
    public static final Resource MappingDirectory = M_MODEL.createResource( "http://w3id.org/rml/MappingDirectory" );
    
    /** <p>Denotes a namespace.</p> */
    public static final Resource Namespace = M_MODEL.createResource( "http://w3id.org/rml/Namespace" );
    
    /** <p>A type of Triples Map that is quoted but not asserted in the resulting graph</p> */
    public static final Resource NonAssertedTriplesMap = M_MODEL.createResource( "http://w3id.org/rml/NonAssertedTriplesMap" );
    
    /** <p>A non nullable annotation is analogous to the notion of NOT NULL constraints 
     *  in databases.</p>
     */
    public static final Resource NonNullableAnnotation = M_MODEL.createResource( "http://w3id.org/rml/NonNullableAnnotation" );
    
    /** <p>Represents an object map.</p> */
    public static final Resource ObjectMap = M_MODEL.createResource( "http://w3id.org/rml/ObjectMap" );
    
    /** <p>Represents a parameter map.</p> */
    public static final Resource ParameterMap = M_MODEL.createResource( "http://w3id.org/rml/ParameterMap" );
    
    /** <p>Represents a parent map</p> */
    public static final Resource ParentMap = M_MODEL.createResource( "http://w3id.org/rml/ParentMap" );
    
    /** <p>Represents a predicate map.</p> */
    public static final Resource PredicateMap = M_MODEL.createResource( "http://w3id.org/rml/PredicateMap" );
    
    /** <p>Represents a predicate-object map.</p> */
    public static final Resource PredicateObjectMap = M_MODEL.createResource( "http://w3id.org/rml/PredicateObjectMap" );
    
    /** <p>A primary key annotation is analogous to the notion of a primary key constraints 
     *  in databases.</p>
     */
    public static final Resource PrimaryKeyAnnotation = M_MODEL.createResource( "http://w3id.org/rml/PrimaryKeyAnnotation" );
    
    /** <p>Denotes a reference to an object map.</p> */
    public static final Resource RefObjectMap = M_MODEL.createResource( "http://w3id.org/rml/RefObjectMap" );
    
    /** <p>Denotes a Reference Formulation.</p> */
    public static final Resource ReferenceFormulation = M_MODEL.createResource( "http://w3id.org/rml/ReferenceFormulation" );
    
    /** <p>Denotes a relative path location.</p> */
    public static final Resource RelativePath = M_MODEL.createResource( "http://w3id.org/rml/RelativePath" );
    
    /** <p>Represents a return map.</p> */
    public static final Resource ReturnMap = M_MODEL.createResource( "http://w3id.org/rml/ReturnMap" );
    
    /** <p>Denotes a source.</p> */
    public static final Resource Source = M_MODEL.createResource( "http://w3id.org/rml/Source" );
    
    /** <p>Represents a star map able to generate RDF-star triples.</p> */
    public static final Resource StarMap = M_MODEL.createResource( "http://w3id.org/rml/StarMap" );
    
    /** <p>Denotes a strategy to perform a action (e.g. gather for collections and containers, 
     *  joins).Denotes a strategy to perform an action or process.</p>
     */
    public static final Resource Strategy = M_MODEL.createResource( "http://w3id.org/rml/Strategy" );
    
    /** <p>A structural annotation provide a mechanism to express relationships between 
     *  logical views, as well as additional information about fields.</p>
     */
    public static final Resource StructuralAnnotation = M_MODEL.createResource( "http://w3id.org/rml/StructuralAnnotation" );
    
    /** <p>Represents a subject map.</p> */
    public static final Resource SubjectMap = M_MODEL.createResource( "http://w3id.org/rml/SubjectMap" );
    
    /** <p>Denotes a target.</p> */
    public static final Resource Target = M_MODEL.createResource( "http://w3id.org/rml/Target" );
    
    /** <p>A function that generates any number of RDF terms from a logical source record.</p> */
    public static final Resource TermMap = M_MODEL.createResource( "http://w3id.org/rml/TermMap" );
    
    /** <p>Represents a triples map.</p> */
    public static final Resource TriplesMap = M_MODEL.createResource( "http://w3id.org/rml/TriplesMap" );
    
    /** <p>Denotes a URI, used with termType.</p> */
    public static final Resource URI = M_MODEL.createResource( "http://w3id.org/rml/URI" );
    
    /** <p>A unique annotation is analogous to the notion of UNIQUE constraints in databases. 
     *  .</p>
     */
    public static final Resource UniqueAnnotation = M_MODEL.createResource( "http://w3id.org/rml/UniqueAnnotation" );
    
    /** <p>Denotes an unsafe IRI, used with termType.</p> */
    public static final Resource UnsafeIRI = M_MODEL.createResource( "http://w3id.org/rml/UnsafeIRI" );
    
    /** <p>Denotes an unsafe URI, used with termType.</p> */
    public static final Resource UnsafeURI = M_MODEL.createResource( "http://w3id.org/rml/UnsafeURI" );
    
    /** <p>Denotes a XPath Reference Formulation.</p> */
    public static final Resource XPathReferenceFormulation = M_MODEL.createResource( "http://w3id.org/rml/XPathReferenceFormulation" );
    
    /** <p>Denotes that the CSV file's column names are used for referring to extracts 
     *  of CSV resources.</p>
     */
    public static final Resource CSV = M_MODEL.createResource( "http://w3id.org/rml/CSV" );
    
    /** <p>Denotes the JSONPath reference formulation, used for referring to extracts 
     *  of JSON sources.</p>
     */
    public static final Resource JSONPath = M_MODEL.createResource( "http://w3id.org/rml/JSONPath" );
    
    /** <p>Denotes a query in SQL 2008.</p> */
    public static final Resource SQL2008Query = M_MODEL.createResource( "http://w3id.org/rml/SQL2008Query" );
    
    /** <p>Denotes a table in SQL 2008.</p> */
    public static final Resource SQL2008Table = M_MODEL.createResource( "http://w3id.org/rml/SQL2008Table" );
    
    /** <p>Represents the UFT-16 encoding.</p> */
    public static final Resource UTF_16 = M_MODEL.createResource( "http://w3id.org/rml/UTF-16" );
    
    /** <p>Represents the UFT-8 encoding.</p> */
    public static final Resource UTF_8 = M_MODEL.createResource( "http://w3id.org/rml/UTF-8" );
    
    /** <p>Denotes the XPath reference formulation, used for referring to extracts of 
     *  XML sources.</p>
     */
    public static final Resource XPath = M_MODEL.createResource( "http://w3id.org/rml/XPath" );
    
    /** <p>Informs that the sets of RDF terms generated by each TermMap of the GatherMap 
     *  are to be appended within the collection or container.</p>
     */
    public static final Resource append = M_MODEL.createResource( "http://w3id.org/rml/append" );
    
    /** <p>Informs that the RDF terms generated by each TermMap of the GatherMap are 
     *  to be grouped (in the constructed collection or container) by doing a Cartesian 
     *  product of these terms.</p>
     */
    public static final Resource cartesianProduct = M_MODEL.createResource( "http://w3id.org/rml/cartesianProduct" );
    
    /** <p>Represents GZip file compression.</p> */
    public static final Resource gzip = M_MODEL.createResource( "http://w3id.org/rml/gzip" );
    
    /** <p>Represents no compression.</p> */
    public static final Resource none = M_MODEL.createResource( "http://w3id.org/rml/none" );
    
    /** <p>Represents TarGZip file compression.</p> */
    public static final Resource targzip = M_MODEL.createResource( "http://w3id.org/rml/targzip" );
    
    /** <p>Represents TarXz file compression.</p> */
    public static final Resource tarxz = M_MODEL.createResource( "http://w3id.org/rml/tarxz" );
    
    /** <p>Represents Zip file compression.</p> */
    public static final Resource zip = M_MODEL.createResource( "http://w3id.org/rml/zip" );

    public static final Property constant = M_MODEL.createProperty( "http://w3id.org/rml/constant" );

    public static final Resource defaultGraph = M_MODEL.createResource( "http://w3id.org/rml/defaultGraph" );
}
