name: Build and Publish Docker image to GHCR

on:
  workflow_dispatch: # allows manual triggers via the GitHub UI
  push:
    branches:
      - 364-publish-docker-image
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx for cross-platform builds (optional but recommended)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to the GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and tag the Docker image
    - name: Build Docker image
      run: |
        cd hefquin-docker/
        docker build -t ghcr.io/liusemweb/hefquin:latest .
        # TODO: Identify tags from commit and loop through these tags and add to the image
        # docker tag ghcr.io/liusemweb/hefquin:latest ghcr.io/liusemweb/hefquin:v1.0.0
    
    # Push the Docker image to GitHub Container Registry (GHCR)
    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/liusemweb/hefquin --all-tags
